CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigoCliente text NOT NULL,
    usuario text NOT NULL,
    nombre text NOT NULL,
    cargo text NOT NULL,
    telefono text NOT NULL,
    correoElectronico text NOT NULL,
    numCel text NOT NULL,
    tiopAcceso text NOT NULL,
    autoriWebStore BOOLEAN NOT NULL,
    autoriOrdens BOOLEAN NOT NULL,
    envioInfo BOOLEAN NOT NULL,
);